#pragma once

#ifndef RHI_SWAP_CHAIN_CLOSE_FULL_SCREEN
#define RHI_SWAP_CHAIN_CLOSE_FULL_SCREEN true
#endif

// TODO 描述符堆Num
#ifndef RHI_DESCRIPTOR_HEAP_SIZE_STANDARD
#define RHI_DESCRIPTOR_HEAP_SIZE_STANDARD 1024
#endif

#ifndef RHI_DESCRIPTOR_HEAP_SIZE_SAMPLER
#define RHI_DESCRIPTOR_HEAP_SIZE_SAMPLER 256
#endif

#ifndef RHI_DESCRIPTOR_HEAP_SIZE_RENDER_TARGET
#define RHI_DESCRIPTOR_HEAP_SIZE_RENDER_TARGET 32
#endif

#ifndef RHI_DESCRIPTOR_HEAP_SIZE_DEPTH_STENCIL
#define RHI_DESCRIPTOR_HEAP_SIZE_DEPTH_STENCIL 32
#endif

#ifndef RHI_MULTI_BUFFERING
#define RHI_MULTI_BUFFERING 2
#endif