#pragma once

#ifndef RHI_SWAP_CHAIN_CLOSE_FULL_SCREEN
#define RHI_SWAP_CHAIN_CLOSE_FULL_SCREEN true
#endif

// TODO 描述符堆Num
#ifndef RHI_DESCRIPTOR_HEAP_SIZE_STANDARD
#define RHI_DESCRIPTOR_HEAP_SIZE_STANDARD 1024
#endif

#ifndef RHI_DESCRIPTOR_HEAP_SIZE_SAMPLER
#define RHI_DESCRIPTOR_HEAP_SIZE_SAMPLER 256
#endif

#ifndef RHI_DESCRIPTOR_HEAP_SIZE_RENDER_TARGET
#define RHI_DESCRIPTOR_HEAP_SIZE_RENDER_TARGET 32
#endif

#ifndef RHI_DESCRIPTOR_HEAP_SIZE_DEPTH_STENCIL
#define RHI_DESCRIPTOR_HEAP_SIZE_DEPTH_STENCIL 32
#endif

/*
* 对于现代API来说我们需要手动的去配置多缓冲区，所以你可以根据需要改变这里的值，
* 注意这里还会创建对应数量的的必要资源，所以值不是越大越好
*/
#ifndef RHI_MULTI_BUFFERING
#define RHI_MULTI_BUFFERING 2
#endif
